Main nav
nancyphak/FullStack pull request #5
Opened 2017-07-20 04:15 UTC by nancyphak

2017-07-20 07:32 UTC, techcoaching requested changes
please rework, if any concern please contact me just make sure the net pull can be approved

2017-07-20 07:32 UTC, techcoaching commented on FrontEnd/index.html
>                      <div class="float-right">
the idea behind is nice, it will be nicer if we can find better name for "float-right"

2017-07-20 07:32 UTC, techcoaching commented on FrontEnd/styles.css
> +.container::before{
We can have more than 1 container in the app, So I think we should change the name to more specifically

2017-07-20 07:32 UTC, techcoaching commented on FrontEnd/styles.css
>  /*Brand end*/
the text in comment region should be in lower case

2017-07-20 07:32 UTC, techcoaching commented on FrontEnd/styles.css
> +.list .item{
It will be better if we can list out the full list of all class for .list component, some can be empty

2017-07-20 07:32 UTC, techcoaching commented on FrontEnd/styles.css
> +.main-nav.list .item{
It will be better if we change to ".main-nav .item"

2017-07-21 11:31 UTC, nancyphak commented on FrontEnd/index.html
> +                <div class="container-size">
@techcoaching I change ''container'' class to "container-size" class but i''m not sure it is better than. If you have any sugguesion please give me  your idea?

2017-07-24 13:17 UTC, closed without merging